# Language selection: en, ru, ua
language: en

# Количество смайликов на одной странице.
page-size: 60

style:
  # Линия-разделитель (глубокий бирюзовый)
  header-line: "&#009688&m----------------------------------------"
  # Заголовок страницы. Используется комбинация яркого и темного RGB.
  title: " &#33D9FF&lIEmoji &#009688| &#E0E0E0Page &#33D9FF%page%&#009688/&#33D9FF%total%"
  # Разделитель между смайликами (пробел)
  separator: " "
  # Цвет стрелочек навигации (Яркий голубой)
  arrow-color: "&#33D9FF"
  # Цвет скобок навигации (Глубокий бирюзовый)
  bracket-color: "&#009688"

# Список смайликов остается тем же
emojis: [
  "❤", "🧡", "💛", "💚", "💙", "💜", "🤎", "🖤", "🤍", "★", "☆", "✪", "✦", "✧", "✶", "✷", "✸", "✹", "☀", "☁", "☂", "☃", "☄", "☎", "☏", "☐", "☑", "☒", "☓", "☔", "☕",
  "☖", "☗", "☘", "☙", "☚", "☛", "☜", "☝", "☞", "☟", "☠", "☡", "☢", "☣", "☤", "☥", "☦", "☧", "☨", "☩", "☪", "☫", "☬", "☭", "☮", "☯", "☸", "☹", "☺", "☻", "☼", "☽", "☾",
  "☿", "♀", "♁", "♂", "♃", "♄", "♅", "♆", "♇", "♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐", "♑", "♒", "♓", "♔", "♕", "♖", "♗", "♘", "♙", "♚", "♛", "♜", "♝", "♞", "♟",
  "♠", "♡", "♢", "♣", "♤", "♥", "♦", "♧", "♨", "♩", "♪", "♫", "♬", "♭", "♮", "♯", "✁", "✂", "✃", "✄", "✆", "✇", "✈", "✉", "✌", "✍", "✎", "✏", "✐", "✑", "✒", "✓", "✔",
  "✕", "✖", "✗", "✘", "✙", "✚", "✛", "✜", "✝", "✞", "✟", "✠", "✡", "✢", "✣", "✤", "✥", "✦", "✧", "✨", "✩", "✪", "✫", "✬", "✭", "✮", "✯", "✰", "✱", "✲", "✳", "✴", "✵",
  "✶", "✷", "✸", "✹", "✺", "✻", "✼", "✽", "✾", "✿", "❀", "❁", "❂", "❃", "❄", "❅", "❆", "❇", "❈", "❉", "❊", "❋", "❍", "❏", "❐", "❑", "❒", "❖", "❘", "❙", "❚", "❛", "❜",
  "❝", "❞", "❡", "❢", "❣", "❤", "❥", "❦", "❧", "❶", "❷", "❸", "❹", "❺", "❻", "❼", "❽", "❾", "❿", "➔", "➘", "➙", "➚", "➛", "➜", "➝", "➞", "➟", "➠", "➡", "➢", "➣", "➤",
  "➥", "➦", "➧", "➨", "➩", "➪", "➫", "➬", "➭", "➯", "➱", "➲", "➳", "➴", "➵", "➶", "➷", "➸", "➹", "➺", "➻", "➼", "➽", "➾", "⚡", "⛔", "⚔", "⚠"
]